# Generated by Django 3.2.1 on 2021-05-04 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SearchStack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
