# Generated by Django 3.2.1 on 2021-05-05 05:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SearchStack', '0002_auto_20210505_0340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='owner_name',
        ),
        migrations.AddField(
            model_name='article',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=datetime.date(1970, 1, 1), null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='link',
            field=models.URLField(default='https://stackoverflow.com/', max_length=250),
        ),
        migrations.AlterField(
            model_name='article',
            name='view_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
