# Generated by Django 3.2.1 on 2021-05-06 23:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SearchStack', '0003_auto_20210505_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('view_count', models.IntegerField(blank=True, null=True)),
                ('link', models.URLField(default='https://stackoverflow.com/', max_length=250)),
                ('creation_date', models.DateTimeField(blank=True, default=datetime.date(1970, 1, 1), null=True)),
            ],
        ),
    ]
